#!/usr/bin/env node
/**
 * receipts.ts — regenerate RECEIPTS.md from a Solscan balance-change CSV export.
 *
 * Usage: node receipts.ts <export_balance_change_*.csv> [metaxUsdPrice]
 *
 * Export the CSV from: solscan.io → your wallet → Transfers → Export.
 * Only incoming transfers of the METAx mint are counted as payouts.
 */

import { readFileSync, writeFileSync } from "node:fs";

const WALLET = "6XgNzJBbo21niRFNCUnuiwaHjeL3RRvn2GwZx9iriKb7";
const METAX_MINT = "Xsa62P5mvPszXL1krVUnU5ar38bBSVcWAB6fmPCo5Zu"; // Meta xStock (METAx) on Solana

const [, , csvPath, priceArg] = process.argv;
if (!csvPath) {
  console.error("usage: node receipts.ts <solscan-export.csv> [metaxUsdPrice]");
  process.exit(1);
}
const usd = priceArg ? Number(priceArg) : null;

const lines = readFileSync(csvPath, "utf8").trim().split(/\r?\n/);
const header = lines[0].split(",").map((h) => h.trim());
const col = (name: string) => header.indexOf(name);
const rows = lines.slice(1).map((l) => l.split(",").map((c) => c.trim()));

const payouts = rows
  .filter(
    (r) =>
      r[col("TokenAddress")] === METAX_MINT && r[col("ChangeType")] === "inc",
  )
  .map((r) => ({
    tx: r[col("Txhash")],
    time: r[col("BlockTime")],
    amount:
      Number(r[col("ChangeAmount")]) / 10 ** Number(r[col("TokenDecimals")]),
  }))
  .sort((a, b) => a.time.localeCompare(b.time));

const total = payouts.reduce((s, p) => s + p.amount, 0);
const days = new Map<string, { n: number; sum: number }>();
for (const p of payouts) {
  const d = p.time.slice(0, 10);
  const e = days.get(d) ?? { n: 0, sum: 0 };
  e.n++;
  e.sum += p.amount;
  days.set(d, e);
}

const fmtUsd = (m: number) => (usd ? ` (~$${(m * usd).toFixed(2)})` : "");
const md = [
  `# Payout receipts`,
  ``,
  `Reward wallet: [\`${WALLET}\`](https://solscan.io/account/${WALLET})`,
  `Reward asset: METAx (Meta xStock), mint [\`${METAX_MINT}\`](https://solscan.io/token/${METAX_MINT})`,
  ``,
  `**${payouts.length} payout transactions, ${total.toFixed(8)} METAx total${fmtUsd(total)}.**`,
  usd
    ? `USD values are approximate at METAx ≈ $${usd} on the generation date; the token tracks META stock and moves with it.`
    : ``,
  `Payouts are funded by creator fees on the attached coin's trading volume, so per-round amounts vary with volume. A score is not payment; these finalized transactions are.`,
  ``,
  `## Per day`,
  ``,
  ...[...days.entries()].map(
    ([d, e]) =>
      `- ${d}: ${e.n} payouts, ${e.sum.toFixed(8)} METAx${fmtUsd(e.sum)}`,
  ),
  ``,
  `## All transactions`,
  ``,
  `| Time (UTC) | METAx | Transaction |`,
  `|---|---|---|`,
  ...payouts.map(
    (p) =>
      `| ${p.time} | ${p.amount.toFixed(8)} | [${p.tx.slice(0, 12)}…](https://solscan.io/tx/${p.tx}) |`,
  ),
  ``,
  `Generated by [receipts.ts](./receipts.ts) from a Solscan balance-change export. Regenerate: \`node receipts.ts <export.csv> <metaxPrice>\``,
].join("\n");

writeFileSync("RECEIPTS.md", md);
console.log(
  `RECEIPTS.md written: ${payouts.length} payouts, ${total.toFixed(8)} METAx${fmtUsd(total)}`,
);
